
name: Modified PR-CI
jobs:
  dist-tar:
    name: dist-tar
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-dist-tar.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/rocketmq/rocketmq', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: touch optcd-3.txt
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '8'
        cache: maven
    - run: touch optcd-4.txt
    - name: Build distribution tar
      run: |-
        mvn -Prelease-all -DskipTests -Dspotbugs.skip=true clean install -U
    - run: touch optcd-5.txt
    - uses: actions/upload-artifact@v4
      name: Upload distribution tar
      with:
        name: rocketmq
        path: distribution/target/rocketmq*/rocketmq*
    - run: touch optcd-6.txt
    - name: Save PR number
      run: |-
        mkdir -p ./pr
        echo ${{ github.event.number }} > ./pr/NR
    - run: touch optcd-7.txt
    - uses: actions/upload-artifact@v4
      with:
        name: pr
        path: pr/
    - run: touch optcd-8.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-dist-tar
        path: /home/runner/inotifywait-log-dist-tar.csv
'on':
- push
- workflow_dispatch
