
name: Modified Run Integration Tests
jobs:
  it-test:
    name: it-test (${{ matrix.os }}, ${{ matrix.jdk }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        jdk:
        - 8
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-it-test (${{ matrix.os }}, ${{ matrix.jdk }}).csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/rocketmq/rocketmq', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - name: Cache Maven Repos
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |-
          ${{ runner.os }}-maven-
    - run: touch optcd-3.txt
    - name: Checkout
      uses: actions/checkout@v2
    - run: touch optcd-4.txt
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: adopt
        cache: maven
    - run: touch optcd-5.txt
    - name: Run integration tests with Maven
      run: mvn clean verify -Pit-test -Pskip-unit-tests
    - run: touch optcd-6.txt
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: test/target/failsafe-reports/TEST-*.xml
        annotate_only: true
        include_passed: true
        detailed_summary: true
    - run: touch optcd-7.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-it-test (${{ matrix.os }}, ${{ matrix.jdk }})
        path: /home/runner/inotifywait-log-it-test (${{ matrix.os }}, ${{ matrix.jdk
          }}).csv
'on':
- push
- workflow_dispatch
