
name: Modified Coverage
jobs:
  calculate-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-calculate-coverage.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/rocketmq/rocketmq', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@master
    - run: touch optcd-3.txt
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: adopt
        cache: maven
    - run: touch optcd-4.txt
    - name: Generate coverage report
      run: mvn -B test -T 2C --file pom.xml
    - run: touch optcd-5.txt
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true
        token: cf0cba0a-22f8-4580-89ab-4f1dec3bda6f
    - run: touch optcd-6.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-calculate-coverage
        path: /home/runner/inotifywait-log-calculate-coverage.csv
    name: calculate-coverage
'on':
- push
- workflow_dispatch
